services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_cache:/var/lib/nginx/cache
    depends_on:
      - front-end
      - books-service
      - orders-service
      - warehouse-service

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  books-service:
    image: node:20
    volumes:
      - ./packages/books:/app
      - ./node_modules:/app/node_modules
    command: npx -y tsx ./index.ts
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - mongo-books
      - rabbitmq

  orders-service:
    image: node:20
    volumes:
      - ./packages/orders:/app
      - ./node_modules:/app/node_modules
    command: npx -y tsx ./index.ts
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - mongo-orders
      - rabbitmq

  warehouse-service:
    image: node:20
    volumes:
      - ./packages/warehouse:/app
      - ./node_modules:/app/node_modules
    command: npx -y tsx ./index.ts
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - mongo-warehouse
      - rabbitmq

  docs-service:
    image: node:20
    volumes:
      - ./packages/docs:/app
      - ./node_modules:/app/node_modules
    command: npx -y tsx ./index.ts
    working_dir: /app

  mongo-books:
    image: mongo:latest
  mongo-orders:
    image: mongo:latest
  mongo-warehouse:
    image: mongo:latest

  rabbitmq:
    image: rabbitmq:4.1.2-management

volumes:
  nginx_cache:
